export const EVENT_DEFAULT_LABEL = 'label (optional)';

export const EVENT_TEST_RESULT_PASSED = 'EVENT_TEST_RESULT_PASSED';
export const EVENT_TEST_RESULT_FAILED = 'EVENT_TEST_RESULT_FAILED';
export const EVENT_TEST_RESULT_NONE = 'EVENT_TEST_RESULT_NONE';

export const EVENT_DEFAULT_TIMEOUT = 5000;